---

- name: Install the Redis packages
  yum: name={{ item }} state=present
  with_items:
    - libselinux-python
    - redis

- name: Set the max open file descriptors
  sysctl: name=vm.overcommit_memory value=1 state=present

- name: start the redis service
  service: name=redis state=started enabled=yes



