---
- name: Install nginx
  yum: name=nginx state=present

- name: Copy nginx configuration
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: http service state
  service: name=nginx state=started enabled=yes

- name: Copy index Template
  template: src=index.html.j2 dest=/usr/share/nginx/html/index.html


