---

- name: Copy the MongoDB repository definition
  copy: src=mongodb-org.repo dest=/etc/yum.repos.d/

- name: Install MongoDB package
  yum:  name={{ item }} state=latest
  with_items:
    - python-pip
    - python-devel
    - mongodb-org

- name: Start MongoDB Service
  service: name=mongod state=started enabled=yes

- name: Install Pymongo
  pip:  name=pymongo version=3.4

- name: add the admin user
  mongodb_user:
    database: admin
    name: admin
    password: ${mongo_admin_pass}
    roles: readWrite,dbAdmin,userAdmin,readWriteAnyDatabase
    state: present
  ignore_errors: yes

- name: Create a new database and a user
  mongodb_user: login_user=admin login_password=${mongo_admin_pass} database=test user=admin password=${mongo_admin_pass} state=present