---

- name: install python
  yum: state=latest name={{ item }}
  with_items:
    - python-pip
    - python-devel

- name: install python package
  pip: name={{ item }}
  with_items:
    - virtualenv
    - gunicorn
    - flask

- name: Creates directory
  file: path=/var/www/MyApp state=directory

- name: Create the virtualenv
  command: virtualenv -p /var/www/MyApp/
           creates=/var/www/MyApp/bin/activate

- name: Ensure gunicorn is installed
  pip: virtualenv=/var/www/MyApp/ name=gunicorn  



