---

- name: install python
  yum: state=latest name={{ item }}
  with_items:
    - python-pip
    - python-devel
    - gcc

- name: install python package
  pip: name=virtualenv

- name: Creates directory
  file: path=/var/www/MyApp state=directory owner=nginx group=nginx

- name: Creates directory
  file: path=/var/www/MyApp/env state=directory owner=nginx group=nginx

- name: Create the virtualenv
  command: virtualenv /var/www/MyApp/env

- name: pip Install packages into virtualenv
  pip: name={{ item }} virtualenv="/var/www/MyApp/env"
  with_items:
    - gunicorn
    - flask

- name: Ensure gunicorn is installed
  pip: virtualenv=/var/www/MyApp/env name=gunicorn

- name: Copy files
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'myapp.py', dest: '/var/www/MyApp/myapp.py' }
    - { src: 'wsgi.py', dest: '/var/www/MyApp/wsgi.py' }
    - { src: 'MyApp.service', dest: '/etc/systemd/system/MyApp.service' }
    - { src: 'gunicorn.conf', dest: '/etc/nginx/conf.d/gunicorn.conf' }

- name: Start MyApp service
  service: name=MyApp state=started enabled=yes

- name: restart nginx
  service: name=nginx state=restarted enabled=yes


