---

- name: install python
  yum: state=latest name={{ item }}
  with_items:
    - python-pip
    - python-devel
    - build-essential
    - uwsgi
    - uwsgi-plugin-python

- name: install python package
  pip: name=virtualenv

- name: Creates directory
  file: path=/var/www/MyApp state=directory owner=nginx group=nginx

- name: Creates directory
  file: path=/var/www/MyApp/.env state=directory owner=nginx group=nginx

- name: Create the virtualenv
  command: virtualenv /var/www/MyApp/.env

- name: pip Install packages into virtualenv
  pip: name={{ item }} virtualenv="/var/www/MyApp/.env"
  with_items:
    - flask

- name: Ensure gunicorn is installed
  pip: virtualenv=/var/www/MyApp/env name=flask

- name: Create Sock File
  file: path=/tmp/myapp.sock owner=nginx group=nginx

- name: Copy files
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'myapp.py', dest: '/var/www/MyApp/myapp.py' }
    - { src: 'gunicorn.conf', dest: '/etc/nginx/conf.d/gunicorn.conf' }
    - { src: 'myapp.ini', dest: '/etc/uwsgi/apps-available/myapp.ini' }

- name: Enable App Link
  command: ln -s /etc/uwsgi/apps-available/myapp.ini /etc/uwsgi/apps-enabled/myapp.ini

- name: Restart nginx
  service: name=nginx state=restarted enabled=yes

- name: Restart uwsgi service
  service: name=uwsgi state=restarted enabled=yes




