---
# This playbook will install MariaDB and create db user and give permissions.

- name: Install MariaDB package
  yum: name={{ item }} state=installed
  with_items:
   - mariadb-server
   - MySQL-python
   - libselinux-python
   - libsemanage-python

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes

- name: Create MariaDB log file
  file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775

- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes

- name: ensure the mariadb root password is set
  mysql_user:
    login_user: root
    name: root
    password: '{{ mysql_root_pw }}'

- name: ensure /root/.my.cnf is present
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: '0600'

- name: ensure anonymous mysql user is absent
  mysql_user:
    name: ''
    login_user: root
    host_all: yes
    state: absent

- name: ensure mysql test database is absent
  mysql_db:
    name: test
    login_user: root
    state: absent

- name: ensure nextcloud database {{ database_mysql_db }} exists
  mysql_db:
    name: '{{ database_mysql_db }}'
    login_user: root
    state: present

- name: ensure database user {{ database_mysql_user }} exists and has all privileges  on {{ database_mysql_db }}
  mysql_user:
    name: '{{ database_mysql_user }}'
    password: '{{ database_mysql_pw }}'
    login_user: root
    priv: '{{ database_mysql_db }}.*:ALL,GRANT'
    state: present

